services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: ""
    container_name: customer-registration-app
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/customer_registration

  postgres:
    image: postgres:16-alpine
    container_name: customer-registration-db

    restart: unless-stopped

    ports:
      - '5432:5432'

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customer_registration

    volumes:
      - postgres16-data:/var/lib/postgresql/data

volumes:
  postgres16-data:
